### ISSUE TITLE
Error while checking authentication

### ISSUE THREAD

**Issue by hazymat** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#5] opened 2021-07-28 21:10 UTC
I just installed Applestrudel, after uninstalling the slightly working but mostly broken alexa-remote2. When I set up the Alexa Account Node, then visit the address http://my-ip:3456 to authenticate, the page is not served up. The node shows error "Error while checking authentication". Any ideas why this may be?

**Comment by Rain-ZG** [comment] 2021-07-31 10:55
set up ip address in config, if you have localhost then it is not working

**Comment by hazymat** [comment] 2021-07-31 22:53
Yes I have done that... the page just isn't served up :/

**Comment by bbindreiter** [comment] 2021-08-01 18:07
Can you check if the node really fires up a webserver and listens on the port? If that's working then I'd guess the problem is some blocking firewall.

**Comment by hazymat** [comment] 2021-08-01 18:33
I have just now recreated the account and it works. Thanks for your help.

**Comment by bbindreiter** [comment] 2021-08-01 18:58
Check the cookie file whether it really contains the cookie. Node-Red needs write access to this file. Or you can try to paste it manually to the file.

**Comment by bbindreiter** [comment] 2021-09-15 06:56
I will close this issue as there is no more activity.

**Closed by bbindreiter** 2021-09-15 06:56 UTC
